In [1]:
import numpy as np

In [5]:
X = np.array([[2,3,4],
         [3,4,5]])

In [4]:
y = np.array([1,2])

In [12]:
np.concatenate([X, np.ones(shape=(X.shape[0], 1))], axis=1)

array([[2., 3., 4., 1.],
       [3., 4., 5., 1.]])

array([[1.],
       [1.]])

In [16]:
np.log1p(5)

1.791759469228055

In [17]:
np.log(6)

1.791759469228055

In [18]:
[1,2,3,4][:-1]

[1, 2, 3]

In [20]:
a = np.random.randn(5, 5)

In [25]:
    grad_x = np.array(a > 0, dtype=int)


In [26]:
grad_x

array([[0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0]])